#!/usr/bin/env bash

{
    #####################################################################
	##### GLOBAL VARIABLES                                          #####
    #####################################################################

    CLEANUP_FILES=""
    DEPS="curl tar"
    EXT="tar.gz"
    DOWNLOAD_DIR="${DOWNLOAD_DIR:-}"
    DOWNLOAD_FILE="tptsh.$EXT"
    DOWNLOAD_PATH=""
    FORCE=0
    KEEP_DOWNLOAD_DIR=0
    PKGS=""
    URL_BASE="https://github.com/TeachersPayTeachers/tpsh/tarball"
    URL=""
    INSTALL_DIR="${INSTALL_DIR:-$HOME/.tpt}"
    INSTALL_FILE="install"
    INSTALL_PATH=""
    RELEASE="${RELASE:-master}"

    #####################################################################
	##### FUNCTIONS                                                 #####
    #####################################################################

    function deps_check() {
        local deps="$@"
        local missing_deps=""
        for dep in $deps; do
            if ! which $dep > /dev/null; then
                missing_deps="$missing_deps $dep"
            fi
        done

        if [ -z "$missing_deps" ]; then
            return 0
        else
            echo "$missing_deps"
            return 1
        fi
    }

    function cleanup() {
        if [ ! -z "$CLEANUP_FILES" ]; then
            log "Cleaning up: $CLEANUP_FILES"
            rm -rf $CLEANUP_FILES
        fi
    }

    function download() {
        local url="$1"
        local download_path="$2"
        curl -sL $url -o $download_path
        if [ $? -ne 0 ] || [ ! -e $download_path ]; then
            return 1
        else
            return 0
        fi
    }

    function install() {
        $INSTALL_PATH $@
        return $?
    }

    function log() {
        echo "[$0] $@"
    }

    function log_err() {
        >&2 log "$@"
    }

    function log_exit() {
        log_err "$@"
        exit 1
    }

    function pkg_add() {
        local pkg="$1"
        $TPSH_PATH pkg add $pkg
        return $?
    }

    function unarchive() {
        local archive="$1"
        local unarchive_dest="$2"
        tar -zxf $archive -C $unarchive_dest --strip-components=1
        return $?
    }

    #####################################################################
	##### PARSE CLI OPTIONS                                         #####
    #####################################################################

    while [ $# -gt 0 ]; do
        arg=$1
        case $arg in
            --download-dir)
              DOWNLOAD_DIR="$2"
              shift
              ;;
            --force)
              FORCE=1
              ;;
            --install-dir)
              INSTALL_DIR="$2"
              shift
              ;;
            --pkg-add)
              PKGS="$PKGS $2"
              shift
              ;;
            --keep-download-dir)
              KEEP_DOWNLOAD_DIR=1
              ;;
			--release)
              RELEASE="$2"
			  shift
              ;; 
        esac
        shift
    done

    #####################################################################
	##### SETUP SIGNAL HANDLER                                      #####
    #####################################################################

    trap cleanup EXIT

    #####################################################################
	##### SET DEFAULTS                                              #####
    #####################################################################

    if [ -z $DOWNLOAD_DIR ]; then
      DOWNLOAD_DIR=$(mktemp -d)
      if [ $KEEP_DOWNLOAD_DIR -eq 0 ]; then
		  CLEANUP_FILES="$CLEANUP_FILES $DOWNLOAD_DIR"
      fi
    fi

    DOWNLOAD_PATH="$DOWNLOAD_DIR/$DOWNLOAD_FILE"
    INSTALL_PATH="$INSTALL_DIR/$INSTALL_FILE"
    TPSH_PATH="$INSTALL_DIR/tpsh"
    URL="$URL_BASE/$RELEASE"

    #####################################################################
	##### MAIN PROGRAM                                              #####
    #####################################################################

    if [ -e "$DOWNLOAD_PATH" ]; then
        log_exit "Download path $DOWNLOAD_PATH already exists"
    fi

    if [ $FORCE -eq 0 ] && [ -e "$INSTALL_DIR" ]; then
        log_exit "Install path $INSTALL_DIR already exists"
    else
        mkdir -p $INSTALL_DIR
    fi

    log "Checking for dependencies: $DEPS"
    missing_deps=$(deps_check $DEPS)
    if [ ! -z "$missing_deps" ]; then
		log_exit "Missing deps: $missing_deps"
    fi
    log "All dependencies are present"

    log "Downloading $URL to $DOWNLOAD_PATH"
    download $URL $DOWNLOAD_PATH \
        || log_exit "Failed to download $URL to $DOWNLOAD_PATH"
    log "Downloaded $URL to $DOWNLOAD_PATH"

    log "Unarchiving $DOWNLOAD_PATH to $INSTALL_DIR"
    unarchive $DOWNLOAD_PATH $INSTALL_DIR \
        || log_exit "Failed to unarchive $DOWNLOAD_PATH to $INSTALL_DIR"
    log "Unarchived $DOWNLOAD_PATH to $INSTALL_DIR"

    log "Running installer $INSTALL_PATH"
    install $INSTALL_PATH \
		|| log_exit "Failed to run installer"
    log "Installer completed successfully!"

    for pkg in $PKGS; do
      log "Installing pkg $pkg"
      pkg_add $pkg \
        || log_exit "Failed to install package $pkg"
      log "Installed pkg $pkg"
    done
}
