#!/usr/bin/env bash

#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__LIB__PKGMGRD__IMPLICIT__DEFINED=${__TPSH__LIB__PKGMGRD__IMPLICIT__DEFINED:-0}
if [ $__TPSH__LIB__PKGMGRD__IMPLICIT__DEFINED -eq 1 ]; then
    return 0
else
    __TPSH__LIB__PKGMGRD__IMPLICIT__DEFINED=1
fi
__TPSH__LIB__PKGMGRD__IMPLICIT__THIS_DIR="$(dirname $BASH_SOURCE)"
__TPSH__LIB__PKGMGRD__IMPLICIT__LIB_DIR="${__TPSH__LIB__PKGMGRD__IMPLICIT__THIS_DIR}/.."

#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__LIB__PKGMGRD__IMPLICIT__LIB_DIR}/logging"
. "${__TPSH__LIB__PKGMGRD__IMPLICIT__LIB_DIR}/pkg"

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_lib_pkgmgrd_implicit_add() {
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    if [ $verbose -eq 1 ]; then
        tpsh_lib_log "pkg ${pkg} is implicitly installed when its dependencies are installed"
    fi

    return 1
}

function tpsh_lib_pkgmgrd_implicit_del() {
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    if [ $verbose -eq 1 ]; then
        tpsh_lib_log_err "pkg ${pkg} will be uninstalled when its dependencies are uninstalled"
    fi

    return 1
}

function tpsh_lib_pkgmgrd_implicit_is_installed() {
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    which $pkg > /dev/null
    result=$?

    if [ $verbose -eq 1 ]; then
        if [ $result -eq 0 ]; then
            tpsh_lib_log "pkg ${pkg} is installed"
        else
            tpsh_lib_log_err "pkg ${pkg} is not installed"
        fi
    fi

    return $result
}
