#!/usr/bin/env bash

#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__LIB__PKGMGRD__PIP__DEFINED=${__TPSH__LIB__PKGMGRD__PIP__DEFINED:-0}
if [ $__TPSH__LIB__PKGMGRD__PIP__DEFINED -eq 1 ]; then
    return 0
else
    __TPSH__LIB__PKGMGRD__PIP__DEFINED=1
fi
__TPSH__LIB__PKGMGRD__PIP__THIS_DIR="$(dirname $BASH_SOURCE)"
__TPSH__LIB__PKGMGRD__PIP__LIB_DIR="${__TPSH__LIB__PKGMGRD__PIP__THIS_DIR}/.."

#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__LIB__PKGMGRD__PIP__LIB_DIR}/logging"

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_lib_pkgmgrd_pip_add() {
    local pkg=""
    local verbose=0
    local version=""

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                elif [ $# -eq 1 ] && [ -z "$version" ]; then
                    version="$arg"
                fi
                ;;
        esac
        shift
    done

    local pip_output=""
    pip_output=$(pip install ${pkg} ${version})
    result=$?

    if [ $verbose -eq 1 ]; then
        local pip_msg_block="\n === begin pip output === \n\n$pip_output\n\n  === end pip output === "
        if [ ! -z "$pip_output" ]; then
            pip_msg_block=""
        fi
        if [ $result -eq 0 ]; then
            tpsh_lib_log "successfully installed ${pkg} ${version} with pip $pip_msg_block"
        else
            tpsh_lib_log_err "failed to install ${pkg} ${version} with pip $pip_msg_block"
        fi
    fi

    return $result;
}

function tpsh_lib_pkgmgrd_pip_del() {
    local pkg=""
    local verbose=0
    local version=""

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                elif [ $# -eq 1 ] && [ -z "$version" ]; then
                    version="$arg"
                fi
                ;;
        esac
        shift
    done

    local pip_output=""
    pip_output=$(echo y | pip uninstall ${pkg} ${version})
    result=$?

    if [ $verbose -eq 1 ]; then
        local pip_msg_block="\n === begin pip output === \n\n$pip_output\n\n  === end pip output === "
        if [ ! -z "$pip_output" ]; then
            pip_msg_block=""
        fi
        if [ $result -eq 0 ]; then
            tpsh_lib_log "successfully uninstalled ${pkg} ${version} with pip $pip_msg_block"
        else
            tpsh_lib_log_err "failed to uninstall ${pkg} ${version} with pip $pip_msg_block"
        fi
    fi

    return $result;
}

function tpsh_lib_pkgmgrd_pip_is_installed() {
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    local pip_output=""
    pip_output=$(pip list $pkg 2>&1)
    result=$?

    if [ $result -eq 1 ]; then
        if [ $verbose -eq 1 ]; then
            local pip_msg_block=""
            if [ ! -z "$pip_output" ]; then
                pip_msg_block="\n === begin pip output === \n\n$pip_output\n\n  === end pip output === "
            fi
            tpsh_lib_log_err "pip does not have any versions of pkg installed: $pkg $pip_msg_block"
        fi
        return $result
    fi

    if [ -z "$version" ]; then
        return $result
    else
        printf "$pip_output" | grep "$version" > /dev/null
        result=$?
    fi

    if [ $verbose -eq 1 ]; then
        local pip_msg_block=""
        if [ ! -z "$pip_output" ]; then
            pip_msg_block="\n === begin pip output === \n\n$pip_output\n\n  === end pip output === "
        fi

        if [ $result -eq 0 ]; then
            tpsh_lib_log "pip does not have pkg installed: $pkg $version $pip_msg_block"
        else
            tpsh_lib_log_err "pip does not have pkg installed: $pkg $version $pip_msg_block"
        fi
    fi

    return $result;
}
