#!/usr/bin/env bash

__TPSH__LIB__LOGGING__DEFINED=${__TPSH__LIB__LOGGING__DEFINED:-0}
if [ $__TPSH__LIB__LOGGING__DEFINED -eq 1 ]; then
    return 0
else
    __TPSH__LIB__LOGGING__DEFINED=1
fi

function tpsh_lib_log() {
    printf "[tpsh] $@\n"
}

function tpsh_lib_log_err() {
    >&2 printf "\033[1;91m[tpsh] $@\033[0m\n"
}

function tpsh_lib_log_err_exit() {
    tpsh_lib_log_err "$@"
    exit 1
}

function tpsh_lib_log_exit() {
    tpsh_lib_log "$@"
    exit 0
}
