#!/usr/bin/env bash


#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__LIB__PKG__DEFINED=${__TPSH__LIB__PKG__DEFINED:-0}
if [ $__TPSH__LIB__PKG__DEFINED -eq 1 ]; then
    return 0
else
    __TPSH__LIB__PKG__DEFINED=1
fi
__TPSH__LIB__PKG__THIS_DIR="$(dirname $BASH_SOURCE)"
__TPSH__LIB__PKG__PKG_DIR="${__TPSH__LIB__PKG__THIS_DIR}/../pkg"

#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__LIB__PKG__THIS_DIR}/logging"
. "${__TPSH__LIB__PKG__THIS_DIR}/platform"

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_lib_pkg_is_managed() {
    local args="$@"
    local generic_fallback=1
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --no-generic-fallback)
                generic_fallback=0
                ;;
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -eq 1 ]; then
                    pkg="$1"
                fi
                ;;
        esac
        shift
    done
}

function tpsh_lib_pkg_is_manageable() {
    local args="$@"
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -eq 1 ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    local pkg_path=""
    pkg_path="$(tpsh_lib_pkg_path $args)" || return $?

    if [ $? -eq 0 ]; then
        return 0
    else
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "management of pkg $pkg is not supported"
        fi
        return 1
    fi
}

function tpsh_lib_pkg_path() {
    local args="$@"
    local generic_fallback=1
    local pkg=""
    local platform="$(tpsh_lib_platform_name)"
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --platform)
                platform="$2"
                shift
                ;;
            --no-generic-fallback)
                generic_fallback=0
                ;;
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    local pkg_path="${__TPSH__LIB__PKG__PKG_DIR}/$pkg"
    if [ ! -e "$pkg_path" ] && [ $generic_fallback -eq 1 ]; then
        pkg_path="${__TPSH__LIB__PKG__PKG_DIR}/generic"
    fi

    if [ ! -e "$pkg_path" ]; then
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "there is no pkg metadata for $pkg at: $pkg_path"
        fi
        return 1
    else
        echo "$pkg_path"
        return 0
    fi
}

function tpsh_lib_pkg_platform_path() {
    local args="$@"
    local platform="$(tpsh_lib_platform_name)"
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --platform)
                platform="$2"
                shift
                ;;
            --verbose)
                verbose=1
                ;;
        esac
        shift
    done

    local pkg_path=""
    pkg_path="$(tpsh_lib_pkg_path $args)" || return $?

    local pkg_platform_path="${pkg_path}/platforms/${platform}"
    if [ -d "$pkg_platform_path" ]; then
        echo $pkg_platform_path
        return 0
    else
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "pkg does not define platform metadata at: $pkg_platform_path"
        fi
        return 1
    fi
}

function tpsh_lib_pkg_supported_pkgmgrs() {
    tpsh_lib_pkg_is_manageable "$@" \
        || return $?

    local args="$@"
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
        esac
        shift
    done

    local pkg_platform_path=""
    pkg_platform_path="$(tpsh_lib_pkg_platform_path $args)" || return $?

    local supported_pkgmgrs_txt="${pkg_platform_path}/supported-pkgmgrs.txt"
    if [ -f "$supported_pkgmgrs_txt" ]; then
        cat $supported_pkgmgrs_txt
        return 0
    else
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "pkg does not define any supported pkgmgrs in: $supported_pkgmgrs_txt"
        fi
        return 1
    fi
}

function tpsh_lib_pkg_supported_platforms() {
    tpsh_lib_pkg_is_manageable "$@" \
        || return $?

    local args="$@"
    local generic_fallback=1
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --platform)
                platform="$2"
                shift
                ;;
            --no-generic-fallback)
                generic_fallback=0
                ;;
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -eq 1 ]; then
                    pkg="$1"
                fi
                ;;
        esac
        shift
    done

    local pkg_path=""
    pkg_path="$(tpsh_lib_pkg_path $args)" || return $?

    local supported_platform_txt="${pkg_path}/supported-platforms.txt"
    if [ ! -e "$supported_platform_txt" ]; then
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "pkg $pkg does not define any supported platforms in: $supported_platform_txt"
        fi
        return 1
    else
        cat $supported_platforms_txt
        return 0
    fi
}

function tpsh_lib_pkg_supports_platform() {
    local args="$@"
    local pkg=""
    local platform="$(tpsh_lib_platform_name)"

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --platform)
                platform="$2"
                shift
                ;;
            -*)
                ;;
            *)
                if [ $# -eq 1 ]; then
                    pkg="$1"
                fi
                ;;
        esac
        shift
    done

    local supported_platforms=""
    supported_platforms="$(tpsh_lib_pkg_supported_platforms $args)" || return $?

    local platform_pattern="$platform"
    if [ $generic_fallback -eq 1 ]; then
        platform_pattern="($platform_pattern\|generic)"
    fi

    if ! printf "$supported_platforms" | grep "$platform_pattern" > /dev/null; then
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "pkg $pkg does not support platform: $platform_pattern"
        fi
    fi
}
