#!/usr/bin/env bash

#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__LIB__PKGMGR__DEFINED=${__TPSH__LIB__PKGMGR__DEFINED:-0}
if [ $__TPSH__LIB__PKGMGR__DEFINED -eq 1 ]; then
    return 0
else
    __TPSH__LIB__PKGMGR__DEFINED=1
fi
__TPSH__LIB__PKGMGR__THIS_DIR="$(dirname $BASH_SOURCE)"
__TPSH__LIB__PKGMGR__PKGMGR_DIR="${__TPSH__LIB__PKGMGR__THIS_DIR}/pkgmgr.d"

#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__LIB__PKGMGR__THIS_DIR}/logging"
. "${__TPSH__LIB__PKGMGR__THIS_DIR}/pkg"
for pkgmgr in $__TPSH__LIB__PKGMGR__PKGMGR_DIR/*; do
    . $pkgmgr
done

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_lib_pkgmgr_current() {
    local args="$@"
    local pkg=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -eq 1 ]; then
                    pkg="$1"
                fi
                ;;
        esac
        shift
    done

    local supported_pkgmgrs="$(tpsh_lib_pkg_supported_pkgmgrs $args)"
    for pkgmgr in $supported_pkgmgrs; do
        if tpsh_lib_pkgmgr_is_installed --pkgmgr $pkgmgr $args; then
            echo $pkgmgr
            return 0
        fi
    done

    if [ $verbose -eq 1 ]; then
        tpsh_lib_log_err "pkg $pkg is not managed by any of its supported pkgmgrs"
    fi

    return 1
}

function tpsh_lib_pkgmgr_is_installed() {
    local args="$@"
    local pkg=""
    local pkgmgr=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --pkgmgr)
                pkgmgr="$2"
                shift
                ;;
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$arg"
                fi
        esac
        shift
    done

    pkgmgr="$(tpsh_lib_pkgmgr_select_preferred $args)"
    >&2 echo PREFERRED PKGMGR $pkgmgr
    tpsh_lib_pkgmgr_is_supported "$args" || return $?
    local pkgmgrd_cmd="tpsh_lib_pkgmgrd_${pkgmgr}_is_installed"
    $pkgmgrd_cmd "$args" || return $?
}

function tpsh_lib_pkgmgr_is_supported() {
    local args="$@"
    local pkgmgr=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --pkgmgr)
                pkgmgr="$2"
                shift
                ;;
            --verbose)
                verbose=1
                ;;
        esac
        shift
    done

    local pkgmgr_path="${__TPSH__LIB__PKGMGR__PKGMGR_DIR}/${pkgmgr}"
    if [ ! -e "$pkgmgr_path" ]; then
        if [ $verbose -eq 1 ]; then
            tpsh_lib_log_err "pkgmgr $pkgmgr is not defined at: $pkgmgr_path"
            return 1
        fi
    fi
}

function tpsh_lib_pkgmgr_select_preferred() {
    local args="$@"
    local pkg=""
    local pkgmgr=""
    local verbose=0

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            --pkgmgr)
                pkgmgr="$2"
                shift
                ;;
            --verbose)
                verbose=1
                ;;
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$arg" ] ; then
                    pkg="$arg"
                fi
                ;;
        esac
        shift
    done

    # User may have requested a pkgmgr
    if [ ! -z "$pkgmgr" ]; then
        echo $pkgmgr
        return 0
    fi

    # Use the preferred pkgmgr of the pkg
    local supported_pkgmgrs="$(tpsh_lib_pkg_supported_pkgmgrs $args)" || return $?
    >&2 echo SUPPORTED PKGMGRS $supported_pkgmgrs
    local preferred_pkgmgr=$(printf "$supported_pkgmgrs" | head -n 1) || return $?
    echo $preferred_pkgmgr
}
