#!/usr/bin/env bash

__TPSH__LIB__PLATFORM__DEFINED=${__TPSH__LIB__PLATFORM__DEFINED:-0}
if [ $__TPSH__LIB__PLATFORM__DEFINED -eq 1 ]; then
    exit
else
    __TPSH__LIB__PLATFORM__DEFINED=1
fi

function tpsh_lib_platform_name() {
    local name=""
    case "$(uname -s)" in
        Darwin*)
            name="darwin"
            ;;
    esac

    if [ ! -z "$name" ]; then
        echo "$name"
        return 0
    else
        return 1
    fi
}
