#!/usr/bin/env bash

__TPSH__LIB__PLATFORM__DEFINED=${__TPSH__LIB__PLATFORM__DEFINED:-0}
if [ $__TPSH__LIB__PLATFORM__DEFINED -eq 1 ]; then
    exit
else
    __TPSH__LIB__PLATFORM__DEFINED=1
fi
__TPSH__LIB__PLATFORM__THIS_DIR="$(dirname $BASH_SOURCE)"
__TPSH__LIB__PLATFORM__PLATFORMD="${__TPSH__LIB__PLATFORM__THIS_DIR}/platform.d"


#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__LIB__PLATFORM__THIS_DIR}/logging"
for pkgmgr in $__TPSH__LIB__PLATFORM__PLATFORMD/*; do
    . $pkgmgr
done

function tpsh_lib_platform_name() {
    local name=""
    case "$(uname -s)" in
        Darwin*)
            name="darwin"
            ;;
    esac

    if [ ! -z "$name" ]; then
        echo "$name"
        return 0
    else
        return 1
    fi
}

function tpsh_lib_platform_version() {
    local platform_name="$(tpsh_lib_platform_name)"
    local platform_version_cmd="tpsh_lib_platformd_${platform_name}_version"
    $platform_version_cmd || return $?
}
