#!/usr/bin/env bash

#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__CMD__HELP__ERROR=0
__TPSH__CMD__HELP__MESSAGE=""

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_cmd_help() {
    cat <<EOF
USAGE: tpsh <cmd> [<command> [args]]
COMMANDS
  help
  pkg
  repo
EOF
}

function tpsh_cmd_help_err() {
    >&2 tpsh_cmd_help
    if [ $# -gt 0 ]; then
        printf "\n\033[1;91m$@\033[0m\n"
    fi
}

#####################################################################
##### PARSE CLI OPTIONS                                         #####
#####################################################################

while [ $# -gt 0 ]; do
    arg="$1"
    case $arg in
        --error)
            __TPSH__CMD__HELP__ERROR=1
            ;;
        *)
            if [ -z "$__TPSH__CMD__HELP__MESSAGE" ]; then
                __TPSH__CMD__HELP__MESSAGE="$arg"
            else
                __TPSH__CMD__HELP__MESSAGE="$__TPSH__CMD__HELP__MESSAGE $arg"
            fi
            ;;
    esac
    shift
done

#####################################################################
##### MAIN PROGRAM                                              #####
#####################################################################

if [ $__TPSH__CMD__HELP__ERROR -eq 1 ]; then
    tpsh_cmd_help_err "$__TPSH__CMD__HELP__MESSAGE"
    exit 1
else
    tpsh_cmd_help
fi
