#!/usr/bin/env bash

#####################################################################
##### GLOBAL VARIABLES                                          #####
#####################################################################

__TPSH__CMD__PKG_VERSION__THIS_DIR="$(dirname $0)"
__TPSH__CMD__PKG_VERSION__LIB_DIR="${__TPSH__CMD__PKG_VERSION__THIS_DIR}/../lib"

#####################################################################
##### LOAD LIBRARIES                                            #####
#####################################################################

. "${__TPSH__CMD__PKG_VERSION__LIB_DIR}/pkgmgr"
. "${__TPSH__CMD__PKG_VERSION__LIB_DIR}/logging"

#####################################################################
##### FUNCTIONS                                                 #####
#####################################################################

function tpsh_cmd_pkg_version() {
    local args="$@"
    local pkg=""

    while [ $# -gt 0 ]; do
        arg="$1"
        case $arg in
            -*)
                ;;
            *)
                if [ $# -le 2 ] && [ -z "$pkg" ]; then
                    pkg="$1"
                fi
                ;;
        esac
        shift
    done

    tpsh_lib_pkgmgr_version "$args"
    result=$?

    if [ $result -ne 0 ]; then
        tpsh_lib_log_err "pkg $pkg version is unknown"
    fi
}

#####################################################################
##### MAIN PROGRAM                                              #####
#####################################################################

tpsh_cmd_pkg_version $@
